# Use an official Node.js image as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install --production

# If you are building your code for production
# RUN npm ci --omit=dev

# Copy the rest of the application code to the container
COPY . .

# Expose the port that your application will run on
EXPOSE 3005

# Define the command to run your application
CMD ["node", "app.js"]
