# Use an official Node.js image as the base image
FROM ubuntu:22.04
FROM node:18

# Set the maintainer label
LABEL maintainer=""

# Set the working directory inside the container
WORKDIR /code

# Copy package.json and package-lock.json to the working directory
COPY package.json ./

# Install dependencies (only production dependencies)
RUN npm install --production

# Copy the rest of the application code to the container
COPY . /code/

# Expose the port that your application will run on
EXPOSE 3000

# Define the command to run your application
CMD ["node", "backend/app.js"]
