# Use an official Python runtime as a parent image
#  this is base image 
FROM python:3.12.4    

# Set the working directory in the container
# this is the working directory of the container 
WORKDIR /app

# Copy the current directory contents into the container at /app
# copy source our machine to destination our container 
COPY . /app

EXPOSE 8080
# Run app.py when the container launches
# its run when container run
CMD ["python", "app.py"]